# Site settings
title: Iain Hull
header-img: img/path.jpg
email: iainhull+blog@gmail.com
description: "Not another software engineering blog"
baseurl: ""
url: "http://iainhull.gihhub.io"
twitter_username: "IainHull"
github_username: "IainHull"

# Build settings
markdown: redcarpet
#markdown: kramdown
#pygments: true
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
